# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a11fd2afdbc830d96cfe8d095e69f3091ce4f3536df5c33d38b8ccaf484f1418d90c173c82bc14f0eba4258e44bd9f0178132668cda1050be33d5c3cef7daaf4

test:
  secret_key_base: 5908c21c49ae0a85d887a3757ac45ebb63d7195d5c567014adf804e54a660922a52bafef2bbfd40347c1af235cf73a8b3aa53e91ffdbf1178dcafade27a5be8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
